### ISSUE TITLE
ValidateRenderImageRule trigger failure after recent ayon-core staging dir update

### ISSUE THREAD

**Issue by kalisp** [ynput/ayon-maya#194]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
`ValidateRendeerImageRule` now triggers as `stagingDir` is filled on the instance and it doesn't match expected value from `workspace.mel`.

Collected value is absolute path to temp dir, expected value is `renders/maya` (eg it expect rendered files to be stored relatively to workfile.

## Expected Behavior
Couple of approaches:
- Logic needs to be redone
- collection of `stagingDir` should be disabled for `render` product type in Maya
- disabling that validator

### Version
`ayon-core` most likely from `1.0.11`

### Relevant log output:

```shell

```

**Comment by BigRoy** [comment]
So unfortunately this seems non-trivial with the current API of the custom staging dir inside `ayon-core`.

For the validator to do what it needs to it'll need to differentiate between whether the instance's staging dir is a custom one - or the "default" one (e.g. a `temporary one in tempdir`). As such, I think we should be adding an additional data key in the `instance.data` that sets `instance.data["stagingdir_custom"] = True` so this validator could just query for that.

@iLLiCiTiT @antirotor thoughts? I'd be happy to make the change in `ayon-core`?

**Comment by antirotor** [comment]
I am not for any guessing and having this flag on instance makes sense.
